- name: Ensure S3 dependencies installed
  pip: 
    name: paramiko
    state: present

- name: Ensure .ssh directory exists.
  file: 
    dest: "{{ duply__sftp_key_file | dirname }}"
    mode: 0700 
    owner: root 
    state: directory

- name: Install ssh private key
  copy: 
    content: "{{ duply__sftp_ssh_key }}" 
    dest: "{{ duply__sftp_key_file }}"
    mode: 0600
    owner: root

- name: Install ssh public key
  copy: 
    content: "{{ duply__sftp_ssk_key_pub }}" 
    dest: "{{ duply__sftp_key_file }}.pub"
    mode: 0600
    owner: root

- name: Ensure SSH config used
  template:
    src: config.sftp.j2
    dest: /root/.ssh/config
    mode: 0600
    owner: root

- name: Ensure duply configuration exists
  template:
    src: "conf.sftp.j2"
    dest: /root/.duply/main/conf
