---
- name: Ensure azure storage client installed
  pip:
    name: azure-storage
    state: present
    version: "0.20.3" # See https://bugs.launchpad.net/duplicity/+bug/1694770
    executable: "{{ duply__pip_executable }}"

- name: Ensure duply configuration exists
  template:
    src: "conf.azure.j2"
    dest: /root/.duply/main/conf
