---
- name: Ensure swift client installed
  pip:
    name: python-swiftclient
    state: present
    executable: "{{ duply__pip_executable }}"

- name: Ensure duply configuration exists
  template:
    src: "conf.swift.j2"
    dest: /root/.duply/main/conf
